#!/usr/bin/bash

# usage: lacluster profile base number

source lapath
source laprofile

# if lock file exists, exit
if [ -f $LOCK_FILE ]; then
    echo "Lock file exists, exiting"
    exit 1
fi

# create lock file
touch $LOCK_FILE

# create number of vms using the profile
for i in $(seq 1 $3); do
    lacreate $(uuidgen) $2 $1
done
